In [5]:
import numpy as np
import sys
s=range(1000)
print("Size of each element of list in bytes :", sys.getsizeof(s))
print("Size of whole list in bytes :", sys.getsizeof(s)*len(s))

Size of each element of list in bytes : 48
Size of whole list in bytes : 48000


In [9]:
d=np.arange(1000)
print("Size of each element of Numpy array in bytes :", d.itemsize)
print("Size of whole Numpy array in bytes :", d.itemsize*d.size)

Size of each element of Numpy array in bytes : 4
Size of whole Numpy array in bytes : 4000


## array are : faster 😦 (OR) occupy less size 😋 : than list 
### list is dynamic while array has fix length

In [10]:
# Create array
import numpy as np
arr = np.array(24)
print(arr)
print(type(arr))
print(arr.ndim)

24
<class 'numpy.ndarray'>
0


In [11]:
# Create array
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,0])
print(arr)
print(type(arr))
print(arr.ndim)

[1 2 3 4 5 6 7 8 9 0]
<class 'numpy.ndarray'>
1


In [44]:
# Create array
import numpy as np
arr = np.array([[1,2,3,4,5]])
print(arr)
print(type(arr))
print(arr.ndim)

[[1 2 3 4 5]]
<class 'numpy.ndarray'>
2


In [24]:
# Create array
import numpy as np
arr = np.array([[[1,2,3,4,5]]])
print(arr)
print(type(arr))
print(arr.ndim)

[[[1 2 3 4 5]]]
<class 'numpy.ndarray'>
3


In [35]:
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr)
print("*********************************")
ar = np.array([[[1,2,3],[4,5]],[[7,8],[10,11,12]]])
print(ar)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
*********************************
[[list([1, 2, 3]) list([4, 5])]
 [list([7, 8]) list([10, 11, 12])]]


<ipython-input-35-a53ce6af24a8>:4: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  ar = np.array([[[1,2,3],[4,5]],[[7,8],[10,11,12]]])


In [42]:
# Create array
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr[2])
print(arr[2]+arr[1])
print(arr[7])

3
5


IndexError: index 7 is out of bounds for axis 0 with size 5

In [63]:
# Create array
import numpy as np
arr = np.array([[1,2,3,4,5]])
print("arr[0][2] :",arr[0][2])
print("arr[0,-2] :",arr[0,-2])
print(arr[:2,:4])
print(arr[:1,2])
print(arr[0][1:])

arr[0][2] : 3
arr[0,-2] : 4
[[1 2 3 4]]
[3]
[2 3 4 5]


### slicing : hase etla bracket [] aavse pan coma , ma nai aave 🙄🙄🙄

In [67]:
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr.shape)
print()
ar = np.array([[[1,2,3],[4,5]],[[7,8],[10,11,12]]])
print(ar.shape)

(2, 2, 3)

(2, 2)


<ipython-input-67-dc9eae933ada>:4: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  ar = np.array([[[1,2,3],[4,5]],[[7,8],[10,11,12]]])


In [68]:
arr = np.array([1,2,3])
print(arr.shape)
#Dhayn rakh 🤑

(3,)


In [81]:
arr = np.array([1,2,3,4,5,6,7,8],ndmin=5)
print(arr)
print(arr.shape)
new=arr.reshape(4,2)
print(new)

[[[[[1 2 3 4 5 6 7 8]]]]]
(1, 1, 1, 1, 8)
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
